import type { CommuneRecord, NearbyCommuneResult, MajorCityResult } from './communes'

/**
 * Great-circle distance using the Haversine formula (km)
 */
export function calculateHaversineDistance(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number
): number {
  const R = 6371 // Earth radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180
  const dLon = ((lon2 - lon1) * Math.PI) / 180
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2)
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a))
  return Number((R * c).toFixed(1))
}

const RAW_FALLBACK_COMMUNES = [
  // ==========================================
  // BRUXELLES-CAPITALE (19 communes)
  // ==========================================
  {
    id: 'c-bruxelles',
    nis_code: '21004',
    name_fr: 'Bruxelles',
    name_nl: 'Brussel',
    slug_fr: 'bruxelles',
    slug_nl: 'brussel',
    postal_codes: ['1000', '1020', '1120', '1130'],
    latitude: 50.8503,
    longitude: 4.3517,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 185103,
    area_km2: 32.61,
    is_active: true,
    is_major_hub: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },
  {
    id: 'c-ixelles',
    nis_code: '21009',
    name_fr: 'Ixelles',
    name_nl: 'Elsene',
    slug_fr: 'ixelles',
    slug_nl: 'elsene',
    postal_codes: ['1050'],
    latitude: 50.8236,
    longitude: 4.3726,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 89120,
    area_km2: 6.34,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },
  {
    id: 'c-uccle',
    nis_code: '21005',
    name_fr: 'Uccle',
    name_nl: 'Ukkel',
    slug_fr: 'uccle',
    slug_nl: 'ukkel',
    postal_codes: ['1180'],
    latitude: 50.7985,
    longitude: 4.3625,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 83703,
    area_km2: 22.91,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },
  {
    id: 'c-schaerbeek',
    nis_code: '21013',
    name_fr: 'Schaerbeek',
    name_nl: 'Schaarbeek',
    slug_fr: 'schaerbeek',
    slug_nl: 'schaarbeek',
    postal_codes: ['1030'],
    latitude: 50.8675,
    longitude: 4.3789,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 133657,
    area_km2: 8.14,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },
  {
    id: 'c-anderlecht',
    nis_code: '21001',
    name_fr: 'Anderlecht',
    name_nl: 'Anderlecht',
    slug_fr: 'anderlecht',
    slug_nl: 'anderlecht',
    postal_codes: ['1070'],
    latitude: 50.8364,
    longitude: 4.3074,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 120455,
    area_km2: 17.74,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },
  {
    id: 'c-etterbeek',
    nis_code: '21008',
    name_fr: 'Etterbeek',
    name_nl: 'Etterbeek',
    slug_fr: 'etterbeek',
    slug_nl: 'etterbeek',
    postal_codes: ['1040'],
    latitude: 50.8328,
    longitude: 4.3878,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 48062,
    area_km2: 3.15,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },
  {
    id: 'c-forest',
    nis_code: '21003',
    name_fr: 'Forest',
    name_nl: 'Vorst',
    slug_fr: 'forest',
    slug_nl: 'vorst',
    postal_codes: ['1190'],
    latitude: 50.8156,
    longitude: 4.3397,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 56040,
    area_km2: 6.25,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },
  {
    id: 'c-saint-gilles',
    nis_code: '21012',
    name_fr: 'Saint-Gilles',
    name_nl: 'Sint-Gillis',
    slug_fr: 'saint-gilles',
    slug_nl: 'sint-gillis',
    postal_codes: ['1060'],
    latitude: 50.8273,
    longitude: 4.3436,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 50165,
    area_km2: 2.52,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },
  {
    id: 'c-molenbeek-saint-jean',
    nis_code: '21015',
    name_fr: 'Molenbeek-Saint-Jean',
    name_nl: 'Sint-Jans-Molenbeek',
    slug_fr: 'molenbeek-saint-jean',
    slug_nl: 'sint-jans-molenbeek',
    postal_codes: ['1080'],
    latitude: 50.8523,
    longitude: 4.3222,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 98671,
    area_km2: 5.89,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },
  {
    id: 'c-woluwe-saint-lambert',
    nis_code: '21014',
    name_fr: 'Woluwe-Saint-Lambert',
    name_nl: 'Sint-Lambrechts-Woluwe',
    slug_fr: 'woluwe-saint-lambert',
    slug_nl: 'sint-lambrechts-woluwe',
    postal_codes: ['1200'],
    latitude: 50.8491,
    longitude: 4.4234,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 58175,
    area_km2: 7.22,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },
  {
    id: 'c-woluwe-saint-pierre',
    nis_code: '21018',
    name_fr: 'Woluwe-Saint-Pierre',
    name_nl: 'Sint-Pieters-Woluwe',
    slug_fr: 'woluwe-saint-pierre',
    slug_nl: 'sint-pieters-woluwe',
    postal_codes: ['1150'],
    latitude: 50.8351,
    longitude: 4.4368,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 41927,
    area_km2: 8.85,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },
  {
    id: 'c-auderghem',
    nis_code: '21002',
    name_fr: 'Auderghem',
    name_nl: 'Oudergem',
    slug_fr: 'auderghem',
    slug_nl: 'oudergem',
    postal_codes: ['1160'],
    latitude: 50.8199,
    longitude: 4.4321,
    province_id: 'p-bruxelles',
    arrondissement_id: 'a-bruxelles',
    population: 35090,
    area_km2: 9.03,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-bruxelles',
      name_fr: 'Bruxelles-Capitale',
      name_nl: 'Brussel Hoofdstedelijk Gewest',
      slug_fr: 'bruxelles-capitale',
    },
  },

  // ==========================================
  // NAMUR (Capitale wallonne & Communes namuroises)
  // ==========================================
  {
    id: 'c-namur',
    nis_code: '92094',
    name_fr: 'Namur',
    name_nl: 'Namen',
    slug_fr: 'namur',
    slug_nl: 'namen-stad',
    postal_codes: ['5000', '5001', '5020'],
    latitude: 50.4669,
    longitude: 4.8675,
    province_id: 'p-namur',
    arrondissement_id: 'a-namur',
    population: 113296,
    area_km2: 175.69,
    is_active: true,
    is_major_hub: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-namur',
      name_fr: 'Namur',
      name_nl: 'Namen',
      slug_fr: 'namur',
    },
  },
  {
    id: 'c-floreffe',
    nis_code: '92045',
    name_fr: 'Floreffe',
    name_nl: 'Floreffe',
    slug_fr: 'floreffe',
    slug_nl: 'floreffe',
    postal_codes: ['5150'],
    latitude: 50.4333,
    longitude: 4.7561,
    province_id: 'p-namur',
    arrondissement_id: 'a-namur',
    population: 8092,
    area_km2: 38.89,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-namur',
      name_fr: 'Namur',
      name_nl: 'Namen',
      slug_fr: 'namur',
    },
  },
  {
    id: 'c-profondeville',
    nis_code: '92101',
    name_fr: 'Profondeville',
    name_nl: 'Profondeville',
    slug_fr: 'profondeville',
    slug_nl: 'profondeville',
    postal_codes: ['5170'],
    latitude: 50.3786,
    longitude: 4.8667,
    province_id: 'p-namur',
    arrondissement_id: 'a-namur',
    population: 12224,
    area_km2: 50.34,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-namur',
      name_fr: 'Namur',
      name_nl: 'Namen',
      slug_fr: 'namur',
    },
  },
  {
    id: 'c-fernelmont',
    nis_code: '92138',
    name_fr: 'Fernelmont',
    name_nl: 'Fernelmont',
    slug_fr: 'fernelmont',
    slug_nl: 'fernelmont',
    postal_codes: ['5380'],
    latitude: 50.5500,
    longitude: 4.9833,
    province_id: 'p-namur',
    arrondissement_id: 'a-namur',
    population: 8072,
    area_km2: 65.61,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-namur',
      name_fr: 'Namur',
      name_nl: 'Namen',
      slug_fr: 'namur',
    },
  },
  {
    id: 'c-andenne',
    nis_code: '92003',
    name_fr: 'Andenne',
    name_nl: 'Andenne',
    slug_fr: 'andenne',
    slug_nl: 'andenne',
    postal_codes: ['5300'],
    latitude: 50.4897,
    longitude: 5.0997,
    province_id: 'p-namur',
    arrondissement_id: 'a-namur',
    population: 27573,
    area_km2: 86.17,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-namur',
      name_fr: 'Namur',
      name_nl: 'Namen',
      slug_fr: 'namur',
    },
  },
  {
    id: 'c-gembloux',
    nis_code: '92142',
    name_fr: 'Gembloux',
    name_nl: 'Gembloers',
    slug_fr: 'gembloux',
    slug_nl: 'gembloers',
    postal_codes: ['5030'],
    latitude: 50.5600,
    longitude: 4.6936,
    province_id: 'p-namur',
    arrondissement_id: 'a-namur',
    population: 26014,
    area_km2: 95.86,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-namur',
      name_fr: 'Namur',
      name_nl: 'Namen',
      slug_fr: 'namur',
    },
  },
  {
    id: 'c-sambreville',
    nis_code: '92137',
    name_fr: 'Sambreville',
    name_nl: 'Sambreville',
    slug_fr: 'sambreville',
    slug_nl: 'sambreville',
    postal_codes: ['5060'],
    latitude: 50.4419,
    longitude: 4.6047,
    province_id: 'p-namur',
    arrondissement_id: 'a-namur',
    population: 28317,
    area_km2: 34.20,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-namur',
      name_fr: 'Namur',
      name_nl: 'Namen',
      slug_fr: 'namur',
    },
  },
  {
    id: 'c-ciney',
    nis_code: '91034',
    name_fr: 'Ciney',
    name_nl: 'Ciney',
    slug_fr: 'ciney',
    slug_nl: 'ciney',
    postal_codes: ['5590'],
    latitude: 50.2953,
    longitude: 5.1006,
    province_id: 'p-namur',
    arrondissement_id: 'a-dinant',
    population: 16698,
    area_km2: 147.56,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-namur',
      name_fr: 'Namur',
      name_nl: 'Namen',
      slug_fr: 'namur',
    },
  },
  {
    id: 'c-dinant',
    nis_code: '91054',
    name_fr: 'Dinant',
    name_nl: 'Dinant',
    slug_fr: 'dinant',
    slug_nl: 'dinant',
    postal_codes: ['5500'],
    latitude: 50.2611,
    longitude: 4.9122,
    province_id: 'p-namur',
    arrondissement_id: 'a-dinant',
    population: 13544,
    area_km2: 99.80,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-namur',
      name_fr: 'Namur',
      name_nl: 'Namen',
      slug_fr: 'namur',
    },
  },

  // ==========================================
  // LIÈGE & BASSIN LIÉGEOIS
  // ==========================================
  {
    id: 'c-liege',
    nis_code: '62063',
    name_fr: 'Liège',
    name_nl: 'Luik',
    slug_fr: 'liege',
    slug_nl: 'luik-stad',
    postal_codes: ['4000', '4020', '4030'],
    latitude: 50.6326,
    longitude: 5.5797,
    province_id: 'p-liege',
    arrondissement_id: 'a-liege',
    population: 197386,
    area_km2: 69.39,
    is_active: true,
    is_major_hub: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-liege',
      name_fr: 'Liège',
      name_nl: 'Luik',
      slug_fr: 'liege',
    },
  },
  {
    id: 'c-seraing',
    nis_code: '62096',
    name_fr: 'Seraing',
    name_nl: 'Seraing',
    slug_fr: 'seraing',
    slug_nl: 'seraing',
    postal_codes: ['4100'],
    latitude: 50.5833,
    longitude: 5.5000,
    province_id: 'p-liege',
    arrondissement_id: 'a-liege',
    population: 64172,
    area_km2: 35.34,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-liege',
      name_fr: 'Liège',
      name_nl: 'Luik',
      slug_fr: 'liege',
    },
  },
  {
    id: 'c-herstal',
    nis_code: '62051',
    name_fr: 'Herstal',
    name_nl: 'Herstal',
    slug_fr: 'herstal',
    slug_nl: 'herstal',
    postal_codes: ['4040'],
    latitude: 50.6639,
    longitude: 5.6319,
    province_id: 'p-liege',
    arrondissement_id: 'a-liege',
    population: 40167,
    area_km2: 23.54,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-liege',
      name_fr: 'Liège',
      name_nl: 'Luik',
      slug_fr: 'liege',
    },
  },
  {
    id: 'c-chaudfontaine',
    nis_code: '62022',
    name_fr: 'Chaudfontaine',
    name_nl: 'Chaudfontaine',
    slug_fr: 'chaudfontaine',
    slug_nl: 'chaudfontaine',
    postal_codes: ['4050'],
    latitude: 50.5833,
    longitude: 5.6333,
    province_id: 'p-liege',
    arrondissement_id: 'a-liege',
    population: 20935,
    area_km2: 25.52,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-liege',
      name_fr: 'Liège',
      name_nl: 'Luik',
      slug_fr: 'liege',
    },
  },
  {
    id: 'c-ans',
    nis_code: '62003',
    name_fr: 'Ans',
    name_nl: 'Ans',
    slug_fr: 'ans',
    slug_nl: 'ans',
    postal_codes: ['4430'],
    latitude: 50.6628,
    longitude: 5.5208,
    province_id: 'p-liege',
    arrondissement_id: 'a-liege',
    population: 28413,
    area_km2: 23.35,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-liege',
      name_fr: 'Liège',
      name_nl: 'Luik',
      slug_fr: 'liege',
    },
  },
  {
    id: 'c-huy',
    nis_code: '61031',
    name_fr: 'Huy',
    name_nl: 'Hoei',
    slug_fr: 'huy',
    slug_nl: 'hoei',
    postal_codes: ['4500'],
    latitude: 50.5186,
    longitude: 5.2417,
    province_id: 'p-liege',
    arrondissement_id: 'a-huy',
    population: 21293,
    area_km2: 47.74,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-liege',
      name_fr: 'Liège',
      name_nl: 'Luik',
      slug_fr: 'liege',
    },
  },
  {
    id: 'c-verviers',
    nis_code: '63079',
    name_fr: 'Verviers',
    name_nl: 'Verviers',
    slug_fr: 'verviers',
    slug_nl: 'verviers',
    postal_codes: ['4800'],
    latitude: 50.5931,
    longitude: 5.8647,
    province_id: 'p-liege',
    arrondissement_id: 'a-verviers',
    population: 55198,
    area_km2: 33.07,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-liege',
      name_fr: 'Liège',
      name_nl: 'Luik',
      slug_fr: 'liege',
    },
  },

  // ==========================================
  // HAINAUT (Charleroi, Mons, Tournai)
  // ==========================================
  {
    id: 'c-charleroi',
    nis_code: '52011',
    name_fr: 'Charleroi',
    name_nl: 'Charleroi',
    slug_fr: 'charleroi',
    slug_nl: 'charleroi',
    postal_codes: ['6000', '6001', '6010'],
    latitude: 50.4109,
    longitude: 4.4444,
    province_id: 'p-hainaut',
    arrondissement_id: 'a-charleroi',
    population: 201555,
    area_km2: 102.08,
    is_active: true,
    is_major_hub: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-hainaut',
      name_fr: 'Hainaut',
      name_nl: 'Henegouwen',
      slug_fr: 'hainaut',
    },
  },
  {
    id: 'c-chatelet',
    nis_code: '52012',
    name_fr: 'Châtelet',
    name_nl: 'Châtelet',
    slug_fr: 'chatelet',
    slug_nl: 'chatelet',
    postal_codes: ['6200'],
    latitude: 50.4042,
    longitude: 4.5269,
    province_id: 'p-hainaut',
    arrondissement_id: 'a-charleroi',
    population: 36101,
    area_km2: 27.03,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-hainaut',
      name_fr: 'Hainaut',
      name_nl: 'Henegouwen',
      slug_fr: 'hainaut',
    },
  },
  {
    id: 'c-courcelles',
    nis_code: '52015',
    name_fr: 'Courcelles',
    name_nl: 'Courcelles',
    slug_fr: 'courcelles',
    slug_nl: 'courcelles',
    postal_codes: ['6180'],
    latitude: 50.4608,
    longitude: 4.3756,
    province_id: 'p-hainaut',
    arrondissement_id: 'a-charleroi',
    population: 31299,
    area_km2: 48.04,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-hainaut',
      name_fr: 'Hainaut',
      name_nl: 'Henegouwen',
      slug_fr: 'hainaut',
    },
  },
  {
    id: 'c-fleurus',
    nis_code: '52021',
    name_fr: 'Fleurus',
    name_nl: 'Fleurus',
    slug_fr: 'fleurus',
    slug_nl: 'fleurus',
    postal_codes: ['6220'],
    latitude: 50.4828,
    longitude: 4.5500,
    province_id: 'p-hainaut',
    arrondissement_id: 'a-charleroi',
    population: 22738,
    area_km2: 59.28,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-hainaut',
      name_fr: 'Hainaut',
      name_nl: 'Henegouwen',
      slug_fr: 'hainaut',
    },
  },
  {
    id: 'c-gerpinnes',
    nis_code: '52025',
    name_fr: 'Gerpinnes',
    name_nl: 'Gerpinnes',
    slug_fr: 'gerpinnes',
    slug_nl: 'gerpinnes',
    postal_codes: ['6280'],
    latitude: 50.3375,
    longitude: 4.5272,
    province_id: 'p-hainaut',
    arrondissement_id: 'a-charleroi',
    population: 12771,
    area_km2: 47.90,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-hainaut',
      name_fr: 'Hainaut',
      name_nl: 'Henegouwen',
      slug_fr: 'hainaut',
    },
  },
  {
    id: 'c-mons',
    nis_code: '55022',
    name_fr: 'Mons',
    name_nl: 'Bergen',
    slug_fr: 'mons',
    slug_nl: 'bergen',
    postal_codes: ['7000', '7012'],
    latitude: 50.4542,
    longitude: 3.9562,
    province_id: 'p-hainaut',
    arrondissement_id: 'a-mons',
    population: 96994,
    area_km2: 146.56,
    is_active: true,
    is_major_hub: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-hainaut',
      name_fr: 'Hainaut',
      name_nl: 'Henegouwen',
      slug_fr: 'hainaut',
    },
  },
  {
    id: 'c-la-louviere',
    nis_code: '58001',
    name_fr: 'La Louvière',
    name_nl: 'La Louvière',
    slug_fr: 'la-louviere',
    slug_nl: 'la-louviere',
    postal_codes: ['7100'],
    latitude: 50.4794,
    longitude: 4.1878,
    province_id: 'p-hainaut',
    arrondissement_id: 'a-soignies',
    population: 80944,
    area_km2: 64.24,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-hainaut',
      name_fr: 'Hainaut',
      name_nl: 'Henegouwen',
      slug_fr: 'hainaut',
    },
  },
  {
    id: 'c-tournai',
    nis_code: '57081',
    name_fr: 'Tournai',
    name_nl: 'Doornik',
    slug_fr: 'tournai',
    slug_nl: 'doornik',
    postal_codes: ['7500'],
    latitude: 50.6056,
    longitude: 3.3881,
    province_id: 'p-hainaut',
    arrondissement_id: 'a-tournai',
    population: 69554,
    area_km2: 213.76,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-hainaut',
      name_fr: 'Hainaut',
      name_nl: 'Henegouwen',
      slug_fr: 'hainaut',
    },
  },
  {
    id: 'c-mouscron',
    nis_code: '57096',
    name_fr: 'Mouscron',
    name_nl: 'Moeskroen',
    slug_fr: 'mouscron',
    slug_nl: 'moeskroen',
    postal_codes: ['7700'],
    latitude: 50.7433,
    longitude: 3.2192,
    province_id: 'p-hainaut',
    arrondissement_id: 'a-tournai',
    population: 58862,
    area_km2: 40.08,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-hainaut',
      name_fr: 'Hainaut',
      name_nl: 'Henegouwen',
      slug_fr: 'hainaut',
    },
  },

  // ==========================================
  // BRABANT WALLON (Wavre, Waterloo, etc.)
  // ==========================================
  {
    id: 'c-wavre',
    nis_code: '25112',
    name_fr: 'Wavre',
    name_nl: 'Waver',
    slug_fr: 'wavre',
    slug_nl: 'waver',
    postal_codes: ['1300'],
    latitude: 50.7175,
    longitude: 4.6122,
    province_id: 'p-brabant-wallon',
    arrondissement_id: 'a-nivelles',
    population: 33801,
    area_km2: 41.80,
    is_active: true,
    is_major_hub: true,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-brabant-wallon',
      name_fr: 'Brabant wallon',
      name_nl: 'Waals-Brabant',
      slug_fr: 'brabant-wallon',
    },
  },
  {
    id: 'c-ottignies-lln',
    nis_code: '25121',
    name_fr: 'Ottignies-Louvain-la-Neuve',
    name_nl: 'Ottignies-Louvain-la-Neuve',
    slug_fr: 'ottignies-louvain-la-neuve',
    slug_nl: 'ottignies-louvain-la-neuve',
    postal_codes: ['1340', '1348'],
    latitude: 50.6667,
    longitude: 4.5667,
    province_id: 'p-brabant-wallon',
    arrondissement_id: 'a-nivelles',
    population: 31385,
    area_km2: 33.97,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-brabant-wallon',
      name_fr: 'Brabant wallon',
      name_nl: 'Waals-Brabant',
      slug_fr: 'brabant-wallon',
    },
  },
  {
    id: 'c-braine-lalleud',
    nis_code: '25014',
    name_fr: 'Braine-l’Alleud',
    name_nl: 'Eigenbrakel',
    slug_fr: 'braine-lalleud',
    slug_nl: 'eigenbrakel',
    postal_codes: ['1420'],
    latitude: 50.6833,
    longitude: 4.3667,
    province_id: 'p-brabant-wallon',
    arrondissement_id: 'a-nivelles',
    population: 40346,
    area_km2: 52.12,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-brabant-wallon',
      name_fr: 'Brabant wallon',
      name_nl: 'Waals-Brabant',
      slug_fr: 'brabant-wallon',
    },
  },
  {
    id: 'c-waterloo',
    nis_code: '25110',
    name_fr: 'Waterloo',
    name_nl: 'Waterloo',
    slug_fr: 'waterloo',
    slug_nl: 'waterloo',
    postal_codes: ['1410'],
    latitude: 50.7177,
    longitude: 4.3986,
    province_id: 'p-brabant-wallon',
    arrondissement_id: 'a-nivelles',
    population: 30174,
    area_km2: 21.03,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-brabant-wallon',
      name_fr: 'Brabant wallon',
      name_nl: 'Waals-Brabant',
      slug_fr: 'brabant-wallon',
    },
  },
  {
    id: 'c-nivelles',
    nis_code: '25072',
    name_fr: 'Nivelles',
    name_nl: 'Nijvel',
    slug_fr: 'nivelles',
    slug_nl: 'nijvel',
    postal_codes: ['1400'],
    latitude: 50.5975,
    longitude: 4.3236,
    province_id: 'p-brabant-wallon',
    arrondissement_id: 'a-nivelles',
    population: 29088,
    area_km2: 60.60,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-brabant-wallon',
      name_fr: 'Brabant wallon',
      name_nl: 'Waals-Brabant',
      slug_fr: 'brabant-wallon',
    },
  },
  {
    id: 'c-rixensart',
    nis_code: '25091',
    name_fr: 'Rixensart',
    name_nl: 'Rixensart',
    slug_fr: 'rixensart',
    slug_nl: 'rixensart',
    postal_codes: ['1330'],
    latitude: 50.7144,
    longitude: 4.5303,
    province_id: 'p-brabant-wallon',
    arrondissement_id: 'a-nivelles',
    population: 22709,
    area_km2: 19.67,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-brabant-wallon',
      name_fr: 'Brabant wallon',
      name_nl: 'Waals-Brabant',
      slug_fr: 'brabant-wallon',
    },
  },
  {
    id: 'c-grez-doiceau',
    nis_code: '25037',
    name_fr: 'Grez-Doiceau',
    name_nl: 'Graven',
    slug_fr: 'grez-doiceau',
    slug_nl: 'graven',
    postal_codes: ['1390'],
    latitude: 50.7389,
    longitude: 4.6953,
    province_id: 'p-brabant-wallon',
    arrondissement_id: 'a-nivelles',
    population: 13915,
    area_km2: 55.44,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-brabant-wallon',
      name_fr: 'Brabant wallon',
      name_nl: 'Waals-Brabant',
      slug_fr: 'brabant-wallon',
    },
  },

  // ==========================================
  // BRABANT FLAMAND (Ceinture périurbaine)
  // ==========================================
  {
    id: 'c-vilvoorde',
    nis_code: '23088',
    name_fr: 'Vilvorde',
    name_nl: 'Vilvoorde',
    slug_fr: 'vilvorde',
    slug_nl: 'vilvoorde',
    postal_codes: ['1800'],
    latitude: 50.9281,
    longitude: 4.4278,
    province_id: 'p-vlaams-brabant',
    arrondissement_id: 'a-hal-vilvorde',
    population: 46314,
    area_km2: 21.48,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-vlaams-brabant',
      name_fr: 'Brabant flamand',
      name_nl: 'Vlaams-Brabant',
      slug_fr: 'brabant-flamand',
    },
  },
  {
    id: 'c-halle',
    nis_code: '23027',
    name_fr: 'Hal',
    name_nl: 'Halle',
    slug_fr: 'hal',
    slug_nl: 'halle',
    postal_codes: ['1500'],
    latitude: 50.7361,
    longitude: 4.2372,
    province_id: 'p-vlaams-brabant',
    arrondissement_id: 'a-hal-vilvorde',
    population: 41243,
    area_km2: 44.40,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-vlaams-brabant',
      name_fr: 'Brabant flamand',
      name_nl: 'Vlaams-Brabant',
      slug_fr: 'brabant-flamand',
    },
  },
  {
    id: 'c-zaventem',
    nis_code: '23094',
    name_fr: 'Zaventem',
    name_nl: 'Zaventem',
    slug_fr: 'zaventem',
    slug_nl: 'zaventem',
    postal_codes: ['1930'],
    latitude: 50.8833,
    longitude: 4.4833,
    province_id: 'p-vlaams-brabant',
    arrondissement_id: 'a-hal-vilvorde',
    population: 35184,
    area_km2: 27.62,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-vlaams-brabant',
      name_fr: 'Brabant flamand',
      name_nl: 'Vlaams-Brabant',
      slug_fr: 'brabant-flamand',
    },
  },
  {
    id: 'c-tervuren',
    nis_code: '24104',
    name_fr: 'Tervuren',
    name_nl: 'Tervuren',
    slug_fr: 'tervuren',
    slug_nl: 'tervuren',
    postal_codes: ['3080'],
    latitude: 50.8242,
    longitude: 4.5147,
    province_id: 'p-vlaams-brabant',
    arrondissement_id: 'a-louvain',
    population: 22861,
    area_km2: 32.92,
    is_active: true,
    is_major_hub: false,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    provinces: {
      id: 'p-vlaams-brabant',
      name_fr: 'Brabant flamand',
      name_nl: 'Vlaams-Brabant',
      slug_fr: 'brabant-flamand',
    },
  },
]
 
export const FALLBACK_COMMUNES: CommuneRecord[] = RAW_FALLBACK_COMMUNES.map((c) => ({
  name_de: null,
  water_hardness_fh: 28,
  transit_axes: ['R0', 'E40', 'E411'],
  ...c,
}))

export function getFallbackCommuneBySlug(slug: string): CommuneRecord | null {
  const normalized = slug.toLowerCase().trim()
  return (
    FALLBACK_COMMUNES.find(
      (c) => c.slug_fr === normalized || c.slug_fr.replace(/-/g, '') === normalized
    ) || null
  )
}

/**
 * Real Haversine geographic proximity calculation
 * Returns true closest neighboring municipalities sorted by distance (km)
 */
export function getFallbackNearbyCommunes(
  currentId: string,
  limit = 6
): NearbyCommuneResult[] {
  const current = FALLBACK_COMMUNES.find((c) => c.id === currentId)
  if (!current) {
    return FALLBACK_COMMUNES.slice(0, limit).map((c, i) => ({
      id: c.id,
      name_fr: c.name_fr,
      slug_fr: c.slug_fr,
      province_name_fr: c.provinces?.name_fr || 'Belgique',
      distance_km: Number((4.0 + i * 2.5).toFixed(1)),
    }))
  }

  return FALLBACK_COMMUNES.filter((c) => c.id !== currentId)
    .map((c) => {
      const distance_km = calculateHaversineDistance(
        current.latitude,
        current.longitude,
        c.latitude,
        c.longitude
      )
      return {
        id: c.id,
        name_fr: c.name_fr,
        slug_fr: c.slug_fr,
        province_name_fr: c.provinces?.name_fr || 'Belgique',
        distance_km,
      }
    })
    .sort((a, b) => a.distance_km - b.distance_km)
    .slice(0, limit)
}

/**
 * Returns nearest Major City Authority Hub for Upward Link equity flow
 */
export function getFallbackNearestMajorHub(
  currentId: string,
  _provinceId?: string
): MajorCityResult | null {
  const current = FALLBACK_COMMUNES.find((c) => c.id === currentId)
  if (!current) return null

  // If already a major hub
  if (current.is_major_hub) {
    // If it's a regional hub other than Brussels city, it can still link up to Brussels if within 30km
    if (current.slug_fr !== 'bruxelles') {
      const bxl = FALLBACK_COMMUNES.find((c) => c.slug_fr === 'bruxelles')
      if (bxl) {
        const dist = calculateHaversineDistance(
          current.latitude,
          current.longitude,
          bxl.latitude,
          bxl.longitude
        )
        if (dist <= 35) {
          return {
            id: bxl.id,
            name_fr: bxl.name_fr,
            slug_fr: bxl.slug_fr,
            distance_km: dist,
          }
        }
      }
    }
    return null
  }

  // Find all major hubs, sort by actual physical distance
  const hubs = FALLBACK_COMMUNES.filter((c) => c.is_major_hub && c.id !== currentId)
  if (hubs.length === 0) return null

  const sortedHubs = hubs
    .map((h) => ({
      id: h.id,
      name_fr: h.name_fr,
      slug_fr: h.slug_fr,
      distance_km: calculateHaversineDistance(
        current.latitude,
        current.longitude,
        h.latitude,
        h.longitude
      ),
    }))
    .sort((a, b) => a.distance_km - b.distance_km)

  return sortedHubs[0] ?? null
}
